#### Where do bedtools and bedops live on your system? ####
# IGNORE - NOW SOLVED BY CONDA ENVIRONMENT
#bedops_path: /SAN/vyplab/alb_projects/tools/bedops/bin/
#bedtools_path: /SAN/vyplab/alb_projects/tools/bedtools

####----------
# SPECIFIC OPTIONS FOR PARSE_STAR_JUNCTIONS.SMK
####----------

####Folders and all the other stuff
####humans

# Top level directory for all output of this run. Must have trailing slash
project_dir: /SAN/vyplab/sbs_projects/pipelines/tectools_pipeline/tectool_output/aligned_bams/junction_counts/

# Name of subdirectory to be generated under project_dir. Sorted BED files will appear here
out_spot: 2021-02-19_parsed_splice_junctions/

# Name of directory containing samples want to analyse. Sample names will be globbed from the filenames in this directory
# If relative path, expect to find bams under {project_dir}/{bam_spot}
# If absolute path, expect to find bams in specified directory
bam_spot: /SAN/vyplab/sbs_projects/pipelines/tectools_pipeline/tectool_output/aligned_bams/

# Suffix of BAM files for samples in bam_spot. Samples pulled like {bam_spot}/{sample_name}{bam_suffix}
bam_suffix: .Aligned.sortedByCoord.out.bam

# Suffix of SJ files for samples in bam_spot generated by STAR. Similiar to bam_suffix
pt1_sj_suffix: .SJ.out.tab

# Path to BED file of target splice junctions you want to quantify
bed_file: /SAN/vyplab/sbs_projects/data/splicing_apa_ipscs/paqr_exon_junction_counts/2021-02-19_ward_ipsc_paqr_last_exons_sjs.bed

# Prefix for final output BED file of junction read counts (for each target junction in bed_file)
# will produce {project_dir}/{out_spot}/{final_output_name}.aggregated.clean.annotated.bed
final_output_name: 2021-02-19_tectool_single_end_1pass_junction_counts


####----------
# SPECIFIC OPTIONS FOR CONVERT_SJ_TO_PSI.SMK
####----------

#### path to annotated gene & transcript models
gtf: /SAN/vyplab/vyplab_reference_genomes/annotation/human/GRCh38/gencode.v34.annotation.gtf

####Folders and all the other stuff - ALL DIRECTORY PATHS SHOULD END IN A SLASH /

# Where to find splice junction files (generated by STAR)
input_sj_folder: /SAN/vyplab/alb_projects/data/sinai_splice_junctions/sinai_all_samples_renamed_sj_tabs/

# Name of subdirectory where output stored. Created underneath input_sj_folder End with trailing slash
out_spot: normalized_annotated/

# Suffix for STAR splice junction files ({sample_name}{sj_suffix})
# Don't usually need to change this
pt2_sj_suffix: .SJ.out.tab

####cell lines
# input_sj_folder = "/SAN/vyplab/alb_projects/data/sinai_splice_junctions/all_bams_kds_linked/sj_files_only/"
